name: Main pipeline

on: push

jobs:
  run_tests:
    name: run_tests
    runs-on: ubuntu-latest
    steps:
      - name: Create environments
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run unit tests
        run: |
          npm install --silent
          npm run coverage

      - name: Create coverage report
        if: always()
        continue-on-error: true # This step shows failure when not all unit tests pass
        run: |
          npm run cov-report

      - name: coveralls
        if: always()
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}